// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC2GVsayPR3WycPfCNJiYMlbelAYspferU',
    appId: '1:534804101911:web:5e6816e6788b290c07d552',
    messagingSenderId: '534804101911',
    projectId: 'bookingapp-58fc9',
    authDomain: 'bookingapp-58fc9.firebaseapp.com',
    storageBucket: 'bookingapp-58fc9.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA2id451S1W4EYsARrt1k-sFy-TjrQnc9Q',
    appId: '1:534804101911:android:0596a484badbd49e07d552',
    messagingSenderId: '534804101911',
    projectId: 'bookingapp-58fc9',
    storageBucket: 'bookingapp-58fc9.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCA4nM5onGcSra_5XfbLk412b2bePF2u4I',
    appId: '1:534804101911:ios:0b33bf9a8ef18e6f07d552',
    messagingSenderId: '534804101911',
    projectId: 'bookingapp-58fc9',
    storageBucket: 'bookingapp-58fc9.appspot.com',
    iosBundleId: 'com.example.travelApplication',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC2GVsayPR3WycPfCNJiYMlbelAYspferU',
    appId: '1:534804101911:web:d23c1ae41ee047fd07d552',
    messagingSenderId: '534804101911',
    projectId: 'bookingapp-58fc9',
    authDomain: 'bookingapp-58fc9.firebaseapp.com',
    storageBucket: 'bookingapp-58fc9.appspot.com',
  );
}
